### ISSUE TITLE
能否只在桌面显示？现在是在浏览器上面也显示

### ISSUE THREAD

**Issue by pooneyy** [DGP-Studio/DGP.Genshin.GamebarWidget#3]
![image](https://user-images.githubusercontent.com/85266337/158307664-5b5158ce-e58e-4dd9-8d04-c87ede8b3a2f.png)

**Comment by pooneyy** [comment]
![image](https://user-images.githubusercontent.com/85266337/158308716-00c93820-8a95-45f3-9dae-7e4bb5d31fe3.png)
如图，真的非常印象日常使用

**Comment by MaxwellYe0815** [comment]
你可以考虑放到任务栏
